### ISSUE TITLE
Is Plus superclass of Unfoldable?

### ISSUE THREAD

**Issue by ursi** [purescript/purescript-unfoldable#28]
This line makes me think `Plus` should be a ~~subclass for~~ superclass of `Unfoldable`.
https://github.com/purescript/purescript-unfoldable/blob/5e392640a2fbe758e8aedc57bad55bc50f16c9cc/src/Data/Unfoldable.purs#L29

**Comment by hdgarrood** [comment]
I don’t think so - in this case, “empty” is meant in a much more loose sense than it is in the Plus hierarchy. In the Plus hierarchy, empty must be an identity element for the <|> operation. Here, it just means that the result doesn’t contain any elements of the type `a`. I’m sure there are valid Plus instances which can’t be given sensible Unfoldable instances. For example, it could make sense to give a Parser type a Plus instance, where <|> tries the parser on the left, and then it if fails, tries the parser on the right. Then empty would be a parser which always fails. I don’t think an Unfoldable instance would make sense for this type.

**Comment by ursi** [comment]
My bad, I had them mixed up in my head. I'm wondering about every `Unfoldable` instance also being a `Plus` instance, not the other way around.

**Comment by hdgarrood** [comment]
I think the same argument applies: the sense of “empty” here is different from the sense of “empty” in the Plus class, which is much more precise, so I’m not sure relating them would necessarily be a good idea.

Admittedly I can’t think of an Unfoldable which is not Plus, and I think all of the Unfoldables I know of are also Plus, and additionally the `empty` from Plus is the same as `unfoldr (const Nothing) unit`. (Those Unfoldables are Maybe, Array, List, lazy List, Seq). But I think there ought to be a stronger reason to add a superclass relationship: I think it shouldn’t just be that it works with existing instances, but that there’s a reason to relate them, in that it makes the class more useful to be able to assume Plus, or there are laws that relate members of the two classes to each other.

You can think of `Unfoldable t` as a slightly more efficient conversion from `List a` to `t a`, since from the point of view of the instance, we’re receiving a sequence of values of that type in a particular order. The `List.toUnfoldable` function sort of demonstrates this. From that perspective, if Plus were to be a superclass of Unfoldable, perhaps some sensible laws would be that `List.toUnfoldable (xs <|> ys) = List.toUnfoldable xs <|> List.toUnfoldable ys`, and `List.toUnfoldable empty = empty`.

However I’m not keen on actually doing this for slightly more pragmatic reasons: firstly, it’s a breaking change for no specific clear benefit, since existing Unfoldable instances would stop compiling if the types in question didn’t already have Plus instances, and secondly, it forces your Alt instance to have a concatenation-like behaviour if you want to provide an Unfoldable instance, which you might not necessarily always want to do.

**Comment by ursi** [comment]
Hm, it just strikes me as wrong that `empty` isn't formalized in any way. I feel like if it's stated in the law then there should be some property that `t a` has to satisfy to qualify as `empty`, and if there is no such property, why even have that law in the first place, as it is essentially meaningless.

Maybe `Plus` isn't the approach to take, but one thing I don't understand is
> and secondly, it forces your Alt instance to have a concatenation-like behaviour if you want to provide an Unfoldable instance

I think I see how this statement can follow from generalizing the laws you wrote above:

> `List.toUnfoldable (xs <|> ys) = List.toUnfoldable xs <|> List.toUnfoldable ys`, and `List.toUnfoldable empty = empty`

But those laws seem like more than is needed. If we had a law that simply formalized the use of `empty` in the existing documentation to mean the `empty` defined by `Plus`, would that still require concatenation behaviour in `Alt` instances? I don't see why it would.

**Comment by hdgarrood** [comment]
It’s not completely meaningless as stated currently, because we already know that the result of `unfoldr (const Nothing) unit` can’t contain any values of the type `a` from parametricity. Also, type classes don’t have to have laws. It’s great when they do, but there are definitely valid ways of using type classes where laws don’t really apply, such as type level computation.

Personally I think `empty` is not really a great name for the thing from Plus, because it is too suggestive - it doesn’t really mean “empty”, but rather an identity element for <|>, which could be any associative operation. In the case of, say, `Const k a`, <|> delegates to the monoid instance of `k`, whose `mempty` might not have anything to do with emptiness, such as 1 for Multiplicative, or `bottom` for Max. Perhaps the best example might be a Monoid instance for a newtype of `Set a` where `a` is BoundedEnum, in which <> is intersection and mempty is a set containing every inhabitant of `a`, the _opposite_ of “empty”.

You could just take the `empty` law and not the <|> law in order to avoid the issue with the Alt instance, but even then it’s difficult because Alt and Unfoldable could still conflict if they want different behaviour out of `empty`. More importantly, I think having a law for `empty`  but not one for <|> would be more difficult to justify, because `empty` doesn’t really mean anything if you take <|> away. This is the core issue: Plus’ empty really just means “identity element for <|>”, which in general doesn’t have to have anything to do with emptiness.

**Comment by ursi** [comment]
> It’s not completely meaningless as stated currently, because we already know that the result of `unfoldr (const Nothing) unit` can’t contain any values of the type `a`

Okay, I think I see what you mean, `unfoldr (const Nothing) b` necessarily has to be "empty" in some sense because there is no way to obtain a value of type `a` for all `a`.

Also I definitely agree with you regarding

> Personally I think empty is not really a great name for the thing from Plus

As a newcomer to all of this, I took `Plus`'s `empty` to be a generalization of what it meant for a data structure to be "empty".

This all leads to another similar question, however. The very next line states your value of type `a` should be "appended" to a structure of type "t a". I take it this "appending" need not be related to `append`? If so, perhaps some different language, e.g. "combined", would be more appropriate?

**Comment by hdgarrood** [comment]
The appending need not be related to "append", but in practice that's basically always what happens, so I think on balance the current language is probably most appropriate.

I think I'm going to close this for now as it seems like there aren't any specific action items for this repo.
